Spa_Management/Controllers/SpaController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Spa_Management.Data;
using Spa_Management.Interfaces;
using Spa_Management.Interfaces.Spa;
using Spa_Management.Models;
using Spa_Management.Operations;

namespace Spa_Management.Controllers
{
    public class SpaController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IDbOperations _dbOps;
        private readonly ISpaOperations _spaOperations;
        private readonly UserManager<ApplicationUser> _userManager;
        public SpaController(ApplicationDbContext context, IDbOperations dbOps, ISpaOperations spaOperations, UserManager<ApplicationUser> manager)
        {
            _dbOps = dbOps;
            _context = context;
            _userManager = manager;
            _spaOperations = spaOperations;
        }
        [AllowAnonymous]
        [HttpGet("/GetPostal/{name}")]
        public IActionResult GetPostal(string name)
        {
            string address = "";
            var name2 = int.Parse(name);
            try
            {
                address = _context.tbPostalCodes.AsNoTracking().FirstOrDefault(c => c.Code == name2).RegionName;
                ViewData["postalAddress"] = address;
                address = address ?? "Address";
            }
            catch (Exception ex)
            {

                throw;
            }

            return Content(address);
        }
        // GET: Spa
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.SpaDetails.ToListAsync());
        //}
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {

            ViewData["spaName"] = String.IsNullOrEmpty(sortOrder) ? "a" : "";
            ViewData["spaReg"] = String.IsNullOrEmpty(sortOrder) ? "b" : "";
            ViewData["spaKra"] = String.IsNullOrEmpty(sortOrder) ? "c" : "";
            ViewData["spaIdNumber"] = String.IsNullOrEmpty(sortOrder) ? "d" : "";
            ViewData["spaLoc"] = String.IsNullOrEmpty(sortOrder) ? "f" : "";
            ViewData["spaPostal"] = String.IsNullOrEmpty(sortOrder) ? "g" : "";
           
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            var ApplicationDbContext = _context.SpaDetails.Include(c => c.SpaUsers).AsQueryable();
           
            #region Sort
            switch (sortOrder)
            {
                case "a":
                    ApplicationDbContext = ApplicationDbContext.OrderBy(m => m.spaName);
                    break;
                case "b":
                    ApplicationDbContext = ApplicationDbContext.OrderBy(m => m.RegCertNo);
                    break;
                case "c":
                    ApplicationDbContext = ApplicationDbContext.OrderBy(m => m.PinNo);
                    break;
                case "d":
                    ApplicationDbContext = ApplicationDbContext.OrderBy(m => m.SpaUsers.FirstOrDefault().idNumber);
                    break;
                case "f":
                    ApplicationDbContext = ApplicationDbContext.OrderBy(m => m.pysicalLoc);
                    break;
                case "g":
                    ApplicationDbContext = ApplicationDbContext.OrderBy(m => m.postalAddress);
                    break;
                default:
                    ApplicationDbContext = ApplicationDbContext.OrderByDescending(m => m.regDate);
                    break;
            }
            #endregion

            int pageSize = 400;
            return View(await PaginatedList<SpaDetails>.CreateAsync(ApplicationDbContext.AsNoTracking(), page ?? 1, pageSize));

        }
        // GET: Spa/Details/5
        public async Task<IActionResult> Details(Guid? id, string f = null)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                var spaDetails = await _context.SpaDetails
                    .SingleOrDefaultAsync(m => m.spaGuid == id);

                if (spaDetails == null)
                {
                    return NotFound();
                }

                var tbcrb = await _context.TbCRBChecks
                .SingleOrDefaultAsync(m => m.compGuid == id);
                if (spaDetails == null)
                {
                    return NotFound();
                }


                var appliedby = await _dbOps.GetSpaRegistrarDetails(spaDetails);

                SpaBusinessDetails det = new SpaBusinessDetails
                {
                    appliedby = appliedby.sirname,
                    spaDetails = spaDetails,
                    ApplicantAddress = appliedby.email,
                    Contact = appliedby.contact,
                    crb = tbcrb
                };
                if (id == null)
                {
                    return NotFound();
                }
              
                ViewData["Gui"] = det.spaDetails.spaGuid;
                ViewData["SpaGuid"] = det.spaDetails.spaGuid;
                ViewData["State0"] = det.spaDetails.status;
               // ViewData["crbStatus"] = det.crb.status;
                if (!object.ReferenceEquals(f, null))
                {
                    ViewData["SpaDetails"] = f;
                }

                return View(det);
            }

            catch (Exception ex)
            {
                await _dbOps.LogError("Spa/Details", "SpaDetails", "", ex.Message.ToString(), ex.InnerException is null ? "N/A" : ex.InnerException.ToString());

            }
            return NotFound();
        }


        [Authorize(Roles = ("MasterAdmin"))]
        public async Task<IActionResult> Verify(string btn, string spaID)
        {
            try
            {
                if (spaID == null)
                {
                    return NotFound();
                }
                Guid gui = Guid.Parse(spaID);

                var spaDet = await _context.SpaDetails
                    .SingleOrDefaultAsync(m => m.spaGuid == gui);

                if (spaDet == null)
                {
                    return NotFound();
                }

                var me = await _userManager.GetUserAsync(HttpContext.User);


                var user = _context.SpaUsers.FirstOrDefault(g => g.spaUserGuid.ToString() == spaDet.registeredBy);
                if (!object.ReferenceEquals(user, null))
                {
                    
                    if (btn == "Verify")
                    {
                        if (spaDet.status == 0)
                        {

                            spaDet.status = 1;
                            var Adduser = new ApplicationUser
                            {
                                UserName = user.email,
                                Email = user.email,
                                spaUserGuid = user.spaUserGuid,
                                PhoneNumber = phoneNumberNomalizer.phoneNum(user.contact),
                                EmailConfirmed = true

                            };
                            //Send Email

                            var pass = _dbOps.GenerateRandomPassword(); 
                            var result = await _userManager.CreateAsync(Adduser, pass);
                            var code = await _userManager.GenerateEmailConfirmationTokenAsync(Adduser);
                            await _userManager.AddToRoleAsync(Adduser, "SPAADMIN");
                            _context.Update(spaDet);
                            await _context.SaveChangesAsync();
                           // String body = " <br /> Click the link here to go to Tradepawa : <a href='https://www.tradepawa.com'></a>";
                            await _dbOps.LogandSendSMS(user.contact, "Dear " + user.FirstName + ", Your Business Registration has been Verified ," + " Your Login Password is " + pass + " and your login email is :" + user.email + " . Kindly keep your password private", "", "", "");
                            await _dbOps.LogAndSendMail(user.email, "Account Password", "Dear " + user.FirstName + ", Your Login Password is " + pass + " and your login email is :" + user.email + " ." + "");
                            return RedirectToAction(nameof(Index));
                        }

                    }
                    if (btn == "Reject")
                    {
                        if (spaDet.status == 0)
                        {

                            spaDet.status = 2;

                            _context.Update(spaDet);
                            await _context.SaveChangesAsync();
                            await _dbOps.LogandSendSMS(user.contact, "Dear " + user.FirstName + " Sorry we could not validate your Business Registration credentials, Please provide valid details", "", "", "");
                            await _dbOps.LogAndSendMail(user.email, "Password", "Dear " + user.FirstName + " Sorry we could not verify your company credentials, Please provide valid details");

                            //Send Email                     
                            return RedirectToAction(nameof(Index));
                        }


                    }
                }

                else
                {
                    return (RedirectToAction("details", new { id = spaID, f = "Applicant Profile is incomplete" }));
                }
                _context.Update(spaDet);
                await _context.SaveChangesAsync();

Spa_Management/Views/Spa/Delete.cshtml
@model Spa_Management.Models.SpaDetails

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SpaDetails</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.registeredBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.registeredBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.spaName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.spaName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.pysicalLoc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.pysicalLoc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.postalAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.postalAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PinNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PinNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RegCertNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RegCertNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.contact)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.contact)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.incNum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.incNum)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.regDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.regDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="spaGuid" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Spa_Management/Views/Spa/Details.cshtml
@*@model Spa_Management.Models.SpaDetails

    @{
        ViewData["Title"] = "Details";
    }

    <h2>Details</h2>

    <div>
        <h4>SpaDetails</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.registeredBy)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.registeredBy)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.spaName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.spaName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.email)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.email)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.pysicalLoc)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.pysicalLoc)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.postalAddress)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.postalAddress)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.PostalCode)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PostalCode)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.PinNo)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PinNo)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.RegCertNo)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.RegCertNo)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.contact)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.contact)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.incNum)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.incNum)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.regDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.regDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.status)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.status)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.spaGuid">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>*@


@model Spa_Management.Controllers.SpaController.SpaBusinessDetails

@{
    ViewData["Title"] = "Details";
}

<div class="panel panel-info ">
    <div class="panel-heading "><h4>Spa Details Details</h4></div>
    <div class="panel-body">
        <div class="text-danger"><label> @ViewBag.SpaDetails</label></div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <table class="table table-hover table-responsive ">
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.appliedby)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.appliedby)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.ApplicantAddress)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.ApplicantAddress)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.Contact)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Contact)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.spaDetails.spaName)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.spaDetails.spaName)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.spaDetails.pysicalLoc)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.spaDetails.pysicalLoc)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.spaDetails.postalAddress)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.spaDetails.postalAddress)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.spaDetails.contact)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.spaDetails.contact)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.spaDetails.RegCertNo)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.spaDetails.RegCertNo)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.spaDetails.PinNo)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.spaDetails.PinNo)
                    </td>
                </tr>


                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.spaDetails.status)</b>
                    </td>
                    <td>

                        @if ((int)ViewBag.State0 == 0)
                        {
                            <button class="btn btn-block btn-default btn-xs">Unverified</button>

                        }
                        else if ((int)ViewBag.State0 == 1)
                        {
                            <button class="btn btn-block btn-info btn-xs">Verified</button>

                        }
                        else if ((int)ViewBag.State0 == 2)
                        {
                            <button class="btn btn-block btn-danger btn-xs">Rejected</button>

                        }

                    </td>
                </tr>


            </table>
        </div>

    </div>
    @if (User.IsInRole("MasterAdmin"))
    {
        <div class="panel panel-primary ">
            <div class="panel-heading "><h4>Business CRB Details</h4></div>

            <div class="panel-body">
                <div class="text-danger"><label>@ViewBag.SpaDetails</label></div>
                @*<p>Tutaziweka Hapa Sasa</p>*@
                <table class="table table-responsive table-striped">
                    <tr>
                        <th>Check Date</th>
                        <th>Score</th>
                        <th>Details</th>
                        <th>Trend</th>
                        <th></th>
                    </tr>
                    <tr>
                        <td>@Html.DisplayFor(model => model.crb.date)</td>

                        <td>@Html.DisplayFor(model => model.crb.score)</td>

                        <td>@Html.DisplayFor(model => model.crb.inComeDetails) </td>

                        <td>@Html.DisplayFor(model => model.crb.details) </td>


                        <td>
                            <a asp-action="CRBDetails" asp-route-id="@ViewBag.Gui">Details</a>
                        </td>

                    </tr>
                </table>
                @if ((int)ViewBag.State0 == 0)
                {
                    <div class="pull-right">
                        <p>
                            <a asp-action="CRBRefresh" asp-route-id="@ViewBag.Gui">Check CRB</a>
                        </p>
                    </div>
                }
            </div>
        </div>
        
    }


</div>

@if (User.IsInRole("MasterAdmin"))
{
    @if ((int)ViewBag.State0 == 0)
    {
        <div class="panel panel-danger">
            <div class="panel-body">
                <form asp-action="Verify" method="post" asp-controller="Spa">
                    <input type="hidden" name="spaID" value="@ViewBag.Gui" />

                    @*<div class="form-group">
                            <label asp-for="SystemBanksGuid" class="control-label"></label>
                            <select id="SystemBanksGuid" name="SystemBanksGuid" asp-for="SystemBanksGuid" class="form-control" asp-items="@(new SelectList(ViewBag.SystemBanksGuid, "SystemBanksGuid","bankName"))" onchange="form.submit();">
                                <option>~ Please Select reason ~ </option>
                            </select>
                        </div>*@

                    <label>Comments</label>
                    <textarea name="Details" class="form-control" placeholder="~ Please add Descriptive comments here ~"></textarea>
                    <div class="pull-right">
                        <p>
                            <div class="row">
                                <table class="table">
                                    <tr>
                                        <td>
                                            <button class="btn btn-block btn-success btn-default" name="btn" value="Verify" type="submit">Verify</button>
                                        </td>
                                        <td>
                                            <button class="btn btn-block btn-danger btn-default" name="btn" value="Reject" type="submit">Reject</button>
                                        </td>
                                        <td>
                                            <a asp-controller="Spa" asp-action="Index" class="btn btn-warning">Back to List</a>
                                        </td>
                                    </tr>
                                </table>

                            </div>
                        </p>
                    </div>
                </form>
            </div>
        </div>
    }
}

Spa_Management/Views/Spa/Edit.cshtml
@model Spa_Management.Models.SpaDetails

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>SpaDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="spaGuid" />
            <div class="form-group">
                <label asp-for="registeredBy" class="control-label"></label>
                <input asp-for="registeredBy" class="form-control" />
                <span asp-validation-for="registeredBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="spaName" class="control-label"></label>
                <input asp-for="spaName" class="form-control" />
                <span asp-validation-for="spaName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="pysicalLoc" class="control-label"></label>
                <input asp-for="pysicalLoc" class="form-control" />
                <span asp-validation-for="pysicalLoc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="postalAddress" class="control-label"></label>
                <input asp-for="postalAddress" class="form-control" />
                <span asp-validation-for="postalAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PinNo" class="control-label"></label>
                <input asp-for="PinNo" class="form-control" />
                <span asp-validation-for="PinNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegCertNo" class="control-label"></label>
                <input asp-for="RegCertNo" class="form-control" />
                <span asp-validation-for="RegCertNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="contact" class="control-label"></label>
                <input asp-for="contact" class="form-control" />
                <span asp-validation-for="contact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="incNum" class="control-label"></label>
                <input asp-for="incNum" class="form-control" />
                <span asp-validation-for="incNum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="regDate" class="control-label"></label>
                <input asp-for="regDate" class="form-control" />
                <span asp-validation-for="regDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="status" class="control-label"></label>
                <input asp-for="status" class="form-control" />
                <span asp-validation-for="status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Spa_Management/Views/Spa/EmailUsed.cshtml
@{
    ViewData["Title"] = "Verification";
}

<div class="row">
    <div class="col-md-9">
        <div class="panel panel-info ">
            <div class="panel-heading "><h4>Business Registration</h4></div>
            <div class="panel-body">
                <p>
                    <b>Business Registration Failed</b>
                </p>
                <p>
                    Dear User, A similar email has been used for registration of a different Spa
                </p>
            </div>
        </div>
    </div>
</div>

Spa_Management/Views/Spa/SpaExists.cshtml
@{
    ViewData["Title"] = "Verification";
}

<div class="row">
    <div class="col-md-9">
        <div class="panel panel-info ">
            <div class="panel-heading "><h4>Business Registration</h4></div>
            <div class="panel-body">
                <p>
                    <b>Business Registration Failed</b>
                </p>
                <p>
                   Dear User, A Spa with similar credentials is already registered.
                </p>
            </div>
        </div>
    </div>
</div>

Spa_Management/Views/Spa/verify.cshtml
@{
    ViewData["Title"] = "Verification";
}

<div class="row">
    <div class="col-md-9">
        <div class="panel panel-info ">
            <div class="panel-heading "><h4>Business Registration Alert</h4></div>
            <div class="panel-body">
                <p>
                    <b>Business Registration Successful</b>
                </p>
                <p>
                    An email with your password will be sent to you once the Spa details have been confirmed.
                    Regards
                </p>
            </div>
        </div>
    </div>
</div>