Spa_Management/Controllers/CompaniesController.cs
using Spa_Management.Data;
using Spa_Management.Interfaces;
using Spa_Management.Models;
using Spa_Management.Operations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Threading.Tasks;
using System.Xml;

namespace Spa_Management.Controllers
{
	public class CompaniesController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly IDbOperations _dbOps;
		private readonly UserManager<ApplicationUser> _userManager;
		public CompaniesController(ApplicationDbContext context, IDbOperations dbOps, UserManager<ApplicationUser> manager)
		{
			_dbOps = dbOps;
			_context = context;
			_userManager = manager;


		}

		// GET: Companies
		public async Task<IActionResult> Index(int id)
		{
            var ApplicationDbContext = id == 0 ? _context.TbCompanies : _context.TbCompanies.AsNoTracking().Where(c => c.status == 0);/*.AsNoTracking().FirstOrDefault(c=>c.status==0)*/;
			return View(await ApplicationDbContext.ToListAsync());
		}

		// GET: Companies/Details/5

		public async Task<IActionResult> Users(Guid? id)
		{
            try
            {
                ViewData["DocumentsVerified"] = true;
                ViewData["DirectorsVerified"] = true;
                ViewData["DirectorsRegistered"] = true;
                ViewData["DocumentsRegistered"] = true;
                if (id == null)
                {
                    return NotFound();
                }
                //ViewData["BankGuid"] = id.Value;
                ViewData["compGuid"] = id.Value;
                ViewData["CompanyName"] = _context.TbCompanies.FirstOrDefault(k => k.compGuid == id).compName;
                var users = await _context.TbCompanyUsers.Where(h => h.compGuid == id).ToListAsync();
                //.SingleOrDefaultAsync(m => m.SystemBanksGuid == id);
                if (users == null)
                {
                    return NotFound();
                }
                List<ViewcompanyUsers> _CompUsers = new List<ViewcompanyUsers>();
                int i = 1;
                foreach (var a in users)
                {
                    ViewcompanyUsers user = new ViewcompanyUsers()
                    {
                        id = i++,
                        compUserGuid = a.compUserGuid,
                        Name = string.Format("{0} {1} {2}", a.SirName, a.FirstName, a.LastName),
                        contact = a.contact,
                        Email = a.email,
                        idNumber = a.idNumber,
                        Role = await _dbOps.GetUserRole(a.compUserGuid, 1),
                        status = a.status
                    };
                    _CompUsers.Add(user);
                }
                ViewData["CompanyName"] = _context.TbCompanies.FirstOrDefault(k => k.compGuid == id).compName;
                ViewData["compGuid"] = id;
                //return View(await ApplicationDbContext.ToListAsync());
                return View(_CompUsers);
            }
            catch (Exception ex)
            {

                await _dbOps.LogError("Companies/Users", "Find Users", "", ex.Message.ToString(), ex.InnerException is null ? "" : ex.InnerException.ToString());
                return NotFound();
            }
			
			//return View(users);
		}

        public async Task<IActionResult> ApproveDocs(string Details1, string btn, string appId)
        {
            try
            {
                if (appId == null)
                {
                    return NotFound();
                }
                Guid gui = Guid.Parse(appId);
                using (_context)
                {
                    var tbCompanyDocs = _context.TbCompanyDocs
                                   .FirstOrDefault(m => m.Id == gui);

                 //   var appicantId = tbCompanyDocs.ApplicantId;

                   // var applicantDetails = _context.TbCompanyUsers.FirstOrDefaultAsync(c => c.compUserGuid == appicantId);


                    if (tbCompanyDocs == null)
                    {
                        return NotFound();
                    }
                    var ToEmail = _context.Users.FirstOrDefault(c => c.Id == tbCompanyDocs.ApplicantId.ToString());
                    if (btn == "Approve")
                    {
                        if (tbCompanyDocs.Status == 0)
                        {
                            tbCompanyDocs.Status = 1;
                            tbCompanyDocs.AdminComments = Details1;
                            tbCompanyDocs.Verified = true;

                            //log info to users
                            //send them mails and sms
                       

                             await _dbOps.LogNotification(tbCompanyDocs.ApplicantId.ToString(), 1, "Your Company Documents have been verified");
                             await _dbOps.LogAndSendMail(ToEmail.Email,"TradePawa Documents Approval","Dear Applicant ,Your Company Documents have been verified successfully");
                        }
                        else
                          if (tbCompanyDocs.Status == 4)
                        {
                            tbCompanyDocs.Status = 5;
                            tbCompanyDocs.Verified = true;
                            tbCompanyDocs.AdminComments = Details1;
                            //Send ammendment acknowledgement
                            await _dbOps.LogNotification(tbCompanyDocs.ApplicantId.ToString(), 1, "Your Company Documents have been verified");
                            await _dbOps.LogAndSendMail(ToEmail.Email, "TradePawa Documents Approval", "Dear Applicant ,Your Company Documents have been verified successfully");
                        }
                        else
                        {
                        }

                    }
                    if (btn == "Reject")
                    {
                        if (tbCompanyDocs.Status == 0)
                        {
                            tbCompanyDocs.Status = 2;
                            tbCompanyDocs.Verified = false;
                            tbCompanyDocs.AdminComments = Details1;
                            await _dbOps.LogNotification(tbCompanyDocs.ApplicantId.ToString(), 1, "Your Company Documents have not been verified . " +Details1);
                            await _dbOps.LogAndSendMail(ToEmail.Email, "TradePawa Documents Approval Declined", "Dear Applicant ,Your Company Documents have not been verified successfully. " +Details1);
                            //     await _dbOps.LogNotification(profile.Id, 1, "Your Application has been Rejected step 1");
                            //_dbOps.logandSendSMS(profile.PhoneNumber, "Your Application has been Rejected step 1");
                        }
                        else
                        if (tbCompanyDocs.Status == 4)
                        {
                            //4 is for ammended one
                            //if rejected flag with 6
                            //if approved flag with 5
                            tbCompanyDocs.Status = 6;
                            tbCompanyDocs.Verified = false;
                            tbCompanyDocs.AdminComments = Details1;
                            await _dbOps.LogNotification(tbCompanyDocs.ApplicantId.ToString(), 1, "Your Company Documents have not been verified . "+Details1);
                            await _dbOps.LogAndSendMail(ToEmail.Email, "TradePawa Documents Approval Declined", "Dear Applicant ,Your Company Documents have not been Verified . "+ Details1 + "");
                        }
                        {


                        }
                    }
                    _context.Update(tbCompanyDocs);
                    _context.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
                //   return RedirectToAction(nameof(Details{ ""}));
            }
            catch (Exception ex)
            {
                await _dbOps.LogError("Companies/ApproveDocs", "Approve Company Docs", "", ex.Message.ToString(), ex.InnerException is null ? "" : ex.InnerException.ToString());

                return RedirectToAction(nameof(Index));
            }
           
        }
        public async Task<IActionResult> Directors(Guid? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                //ViewData["BankGuid"] = id.Value;
                ViewData["compGuid"] = id.Value;
                ViewData["CompanyName"] = _context.TbCompanies.FirstOrDefault(k => k.compGuid == id).compName;
                var users = await _context.TbDirectors.Where(h => h.CompanyId == id).ToListAsync();
                //.SingleOrDefaultAsync(m => m.SystemBanksGuid == id);
                if (users == null)
                {
                    return NotFound();
                }
                List<ViewcompanyDirectors> _CompUsers = new List<ViewcompanyDirectors>();
                int i = 1;
                foreach (var a in users)
                {
                    ViewcompanyDirectors user = new ViewcompanyDirectors()
                    {
                        id = i++,
                        DirectorId = a.Id,
                        FirsName = a.FirstName, //string.Format("{0} {1}", a.FirstName, a.LastName),
                        TelephoneNumber = a.TelephoneNumber,
                        Email = a.Email,
                        idNumber = a.IdNumber,
                        LastName = a.LastName,
                        MiddleName = a.MiddleName,
                        // Role = await _dbOps.GetUserRole(a.compUserGuid, 1),
                        status = a.Verified
                    };

Spa_Management/Views/Companies/AttachmentDetails.cshtml
@*@{
        ViewData["Title"] = "AttachmentDetails";
    }

    <h2>AttachmentDetails</h2>*@

@model Spa_Management.Controllers.CompanyDocumentDetails

@{
    ViewData["Title"] = "Attachment Details";
}



<div class="panel panel-info ">
    <div class="panel-heading "><h4>Attachment Details</h4></div>
    <div class="panel-body">
        <div class="text-danger"><label> @ViewBag.CompanyDocumentDetails</label></div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <table class="table table-hover table-responsive ">
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.compDocs.PinCertificate)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.compDocs.PinCertificate)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.compDocs.Cr12)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.compDocs.Cr12)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.compDocs.RegistrationCertificate)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.compDocs.RegistrationCertificate)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.compDocs.BoardResolution)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.compDocs.BoardResolution)
                    </td>
                </tr> 
            </table>
        </div>
    </div>
</div>

Spa_Management/Views/Companies/Details.cshtml
@model Spa_Management.Controllers.CompanyDetails

@{
    ViewData["Title"] = "Details";
}

<div class="panel panel-info ">
    <div class="panel-heading "><h4>Company Details</h4></div>
    <div class="panel-body">
        <div class="text-danger"><label> @ViewBag.CompanyDetails</label></div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <table class="table table-hover table-responsive ">
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.appliedby)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.appliedby)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.ApplicantAddress)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.ApplicantAddress)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.Contact)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Contact)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.company.compName)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.company.compName)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.company.pysicalLoc)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.company.pysicalLoc)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.company.postalAddress)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.company.postalAddress)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.company.contact)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.company.contact)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.company.RegCertNo)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.company.RegCertNo)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.company.PinNo)</b>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.company.PinNo)
                    </td>
                </tr>


                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.company.status)</b>
                    </td>
                    <td>

                        @if ((int)ViewBag.State0 == 0)
                        {
                            <button class="btn btn-block btn-default btn-xs">Unverified</button>

                        }
                        else if ((int)ViewBag.State0 == 1)
                        {
                            <button class="btn btn-block btn-info btn-xs">Verified</button>

                        }
                        else if ((int)ViewBag.State0 == 2)
                        {
                            <button class="btn btn-block btn-danger btn-xs">Rejected</button>

                        }

                    </td>
                </tr>


            </table>
        </div>

    </div>
    @if (User.IsInRole("MasterAdmin"))
    {
        @if ((int)ViewBag.State0 == 0)
        {
            <div class="panel panel-danger">
                <div class="panel-body">
                    <form asp-action="Verify" method="post" asp-controller="Companies">
                        <input type="hidden" name="compID" value="@ViewBag.Gui" />

                        @*<div class="form-group">
                                <label asp-for="SystemBanksGuid" class="control-label"></label>
                                <select id="SystemBanksGuid" name="SystemBanksGuid" asp-for="SystemBanksGuid" class="form-control" asp-items="@(new SelectList(ViewBag.SystemBanksGuid, "SystemBanksGuid","bankName"))" onchange="form.submit();">
                                    <option>~ Please Select reason ~ </option>
                                </select>
                            </div>*@

                        <label>Comments</label>
                        <textarea name="Details" class="form-control" placeholder="~ Please add Descriptive comments here ~"></textarea>
                        <div class="pull-right">
                            <p>
                                <div class="row">
                                    <table class="table">
                                        <tr>
                                            <td>
                                                <button class="btn btn-block btn-success btn-default" name="btn" value="Verify" type="submit">Verify</button>
                                            </td>
                                            <td>
                                                <button class="btn btn-block btn-danger btn-default" name="btn" value="Reject" type="submit">Reject</button>
                                            </td>
                                        </tr>
                                    </table>

                                </div>
                            </p>
                        </div>
                    </form>
                </div>
            </div>
        }
    }

</div>
@if (User.IsInRole("MasterAdmin"))
{
    <div class="panel panel-primary ">
        <div class="panel-heading "><h4>CRB Details</h4></div>

        <div class="panel-body">
            <div class="text-danger"><label>@ViewBag.CompanyDetails</label></div>
            @*<p>Tutaziweka Hapa Sasa</p>*@
            <table class="table table-responsive table-striped">
                <tr>
                    <th>Check Date</th>
                    <th>Score</th>
                    <th>Details</th>
                    <th>Trend</th>
                    <th></th>
                </tr>
                <tr>
                    <td>@Html.DisplayFor(model => model.crb.date)</td>

                    <td>@Html.DisplayFor(model => model.crb.score)</td>

                    <td>@Html.DisplayFor(model => model.crb.inComeDetails) </td>

                    <td>@Html.DisplayFor(model => model.crb.details) </td>


                    <td>
                        <a asp-action="CRBDetails" asp-route-id="@ViewBag.Gui">Details</a>
                    </td>

                </tr>
            </table>
            @if ((int)ViewBag.State0 == 0)
            {
                <div class="pull-right">
                    <p>
                        <a asp-action="CRBRefresh" asp-route-id="@ViewBag.Gui">Check CRB</a>
                    </p>
                </div>
            }
        </div>
    </div>
    <div class="panel panel-primary ">
        <div class="panel-heading "><h4>Company Attachments</h4></div>

        <div class="panel-body">
            <div class="text-danger"><label>@ViewBag.CompanyDocumentDetails</label></div>
            @*<p>Tutaziweka Hapa Sasa</p>*@
            <table class="table table-responsive table-striped">
                <tr>
                    <th>Board Resolution</th>
                    <th>Pin Certificate</th>
                    <th>Registration Certificate</th>
                    <th>CR12 Form</th>
                    <th>Status</th>
                    <th>Action</th>
                    <th></th>
                </tr>
                <tr>
                    @if ((int)ViewBag.DocState0 != 20)
                    {
                        <td>
                            <a asp-controller="CompanyDocs" asp-action="Download" asp-route-filename="@ViewBag.BoardResolutionDocPath">Download</a>
                        </td>
                        <td>
                            <a asp-controller="CompanyDocs" asp-action="Download" asp-route-filename="@ViewBag.PinCertDocPath">Download</a>
                        </td>
                        <td>
                            <a asp-controller="CompanyDocs" asp-action="Download" asp-route-filename="@ViewBag.RegCertDocPath">Download</a>
                        </td>
                        <td>
                            <a asp-controller="CompanyDocs" asp-action="Download" asp-route-filename="@ViewBag.Cr12DocPath">Download</a>
                        </td>

                        <td>
                            @if ((int)ViewBag.DocState0 == 0)
                            {
                                <button class="btn btn-block btn-default btn-xs">Pending</button>

                            }
                            else if ((int)ViewBag.DocState0 == 1)
                            {
                                <button class="btn btn-block btn-success btn-xs">Verified</button>

                            }
                            else if ((int)ViewBag.DocState0 == 2)
                            {

                                <button class="btn btn-block btn-danger btn-xs">Rejected</button>
                            }
                            else if ((int)ViewBag.DocState0 == 3)
                            {

                                <button class="btn btn-block btn-success btn-xs">Verified</button>
                            }
                            @if ((int)ViewBag.DocState0 == 4)
                            {
                                <button class="btn btn-block btn-default btn-xs">Verify Ammended</button>
                            }
                            else if ((int)ViewBag.DocState0 == 5)
                            {

                                <button class="btn btn-block btn-success btn-xs">Ammends Approved</button>
                            }
                            else if ((int)ViewBag.DocState0 == 6)
                            {

                                <button class="btn btn-block btn-danger btn-xs">Ammends Rejected</button>
                            }
                        </td>
                        <td>
                            <a asp-controller="CompanyDocs" asp-action="Details" asp-route-id="@ViewBag.Gui">View Attachments</a>
                        </td>
                    }

                </tr>


            </table>
        </div>






    </div>
    <div class="panel panel-primary ">
        <div class="panel-heading "><h4>List Of Directors</h4></div>

        <div class="panel-body">
            <div class="text-danger"><label>@ViewBag.CompanyDetails</label></div>
            @*<p>Tutaziweka Hapa Sasa</p>*@
            <table class="table table-responsive table-striped">
                <tr>
                    <th>First Name</th>
                    <th>Middle Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>TelephoneNumber</th>
                    <th>Status</th>
                    <th> </th>


                </tr>
                @foreach (var item in Model.directors)
                {
                    <tr>
                        <td>@Html.DisplayFor(model => item.FirstName)</td>

                        <td>@Html.DisplayFor(model => item.MiddleName)</td>

                        <td>@Html.DisplayFor(model => item.LastName)</td>

                        <td>@Html.DisplayFor(model => item.Email) </td>

                        <td>@Html.DisplayFor(model => item.TelephoneNumber) </td>

                        <td>
                            @if (item.Verified == true)
                            {
                                <button class="btn btn-block btn-success btn-xs">Verified</button>

                            }
                            else
                            {

                                <button class="btn btn-block btn-danger btn-xs">Unverified</button>
                            }
                        </td>
                        @if (item.Verified == true)
                        {
                            @*<td>
                                    <a asp-action="CRBDetails" asp-route-id="@ViewBag.Gui">View Details</a>
                                </td>*@
                        }
                        else
                        {
                            <td>
                                <a asp-controller="tbDirectors" asp-action="Details" asp-route-id="@item.Id">Verify Director</a>
                                @*<a asp-action="VerifyDirectors" asp-route-id="@item.Id">Verify Director</a>*@
                            </td>

                        }


                    </tr>
                }

            </table>
        </div>

    </div>
    <div>
        <a asp-controller="Companies" asp-action="Index"  class="btn btn-warning">Back to List</a>
    </div>
}

Spa_Management/Views/Companies/VerifyDirectors.cshtml
@model Spa_Management.Controllers.ViewcompanyDirectors
@{
    ViewData["Title"] = "Directors";
}


<section class="content">
    <div class="row">
        <div class="box">
            <div class="box-body">
                <div class="panel panel-info ">
                    <div class="panel-heading "><h4>Company Directors - @ViewBag.CompanyName</h4></div>
                    <div class="panel-body">
                        <table id="example1" class="table table-bordered table-striped table-responsive">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.id)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.FirsName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.TelephoneNumber)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Email)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.idNumber)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.status)
                                    </th>

                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem =>modelItem.id)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => modelItem.FirsName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => modelItem.TelephoneNumber)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => modelItem.Email)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => modelItem.idNumber)
                                        </td>
                                        <td>
                                            @if (Model.status== true)
                                            {
                                                <button class="btn btn-block btn-success btn-xs">Verified</button>

                                            }
                                            else
                                            {

                                                <button class="btn btn-block btn-danger btn-xs">Unverified</button>
                                            }
                                        </td>
                                    </tr>

                            </tbody>
                        </table>
                        @if (User.IsInRole("MasterAdmin"))
                        {
                            @if (Model.status==false)
                            {
                                <div class="panel panel-danger">
                                    <div class="panel-heading "><h4>Approve / Reject </h4></div>
                                    <div class="panel-body">
                                        <form asp-action="VerifyDirectors" method="post" asp-controller="Companies">
                                            <input type="hidden" name="compDirID" value="" />
                                            <div>
                                                <label>Comments</label>
                                                <textarea name="Details" class="form-control" placeholder="~ Please add Descriptive comments here ~"></textarea>
                                            </div>
                                            <div class="pull-right">
                                                <p>
                                                    <div class="row">
                                                        <table class="table">
                                                            <tr>
                                                                <td>
                                                                    <button class="btn btn-block btn-success btn-default" name="btn" value="Approve" type="submit">Approve</button>
                                                                </td>
                                                                <td>
                                                                    <button class="btn btn-block btn-danger btn-default" name="btn" value="Reject" type="submit">Reject</button>
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </div>
                                                </p>
                                            </div>

                                        </form>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
                <div>

                </div>
              
                <div>
                    <a asp-controller="Companies" asp-action="Details" asp-route-id="@ViewBag.Gui">Back to List</a>
                </div>
            </div>
        </div>
    </div>

</section>

<script>
    $(function () {
        $("#example1").DataTable(
            {
                "ordering": false
            }
        );

    });
</script>